# Generated by Django 6.0.8 on 2026-09-17 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('garage', '0001_initial'),
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='От кого'),
        ),
        migrations.AddField(
            model_name='order',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_content_object', to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Изменено'),
        ),
        migrations.AddField(
            model_name='orderaccount',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordersaccount', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заявки'),
        ),
        migrations.AddField(
            model_name='orderaccount',
            name='support_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supportspecialist', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='orderaho',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordersaho', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заявки'),
        ),
        migrations.AddField(
            model_name='orderaho',
            name='support_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supportspecialist', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='orderpc',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderspc', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заявки'),
        ),
        migrations.AddField(
            model_name='orderpc',
            name='support_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supportspecialist', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='orderprinter',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordersprinter', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='orderprinter',
            name='support_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supportspecialist', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='ordertransport',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_transport', to='garage.driver', verbose_name='Водитель'),
        ),
        migrations.AddField(
            model_name='ordertransport',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_transport', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='ordertransport',
            name='support_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supportspecialist', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='ordervks',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordersvks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель заявки'),
        ),
        migrations.AddField(
            model_name='ordervks',
            name='support_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.supportspecialist', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='orderworkflowrule',
            name='content_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_workflow_rule', to='contenttypes.contenttype', verbose_name='Тип заявки'),
        ),
        migrations.AddField(
            model_name='orderworkflowrule',
            name='eligible_specialists',
            field=models.ManyToManyField(blank=True, related_name='order_workflow_rules', to='users.supportspecialist', verbose_name='Доступные исполнители'),
        ),
        migrations.AddField(
            model_name='orderworkflowrule',
            name='last_assigned_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.supportspecialist', verbose_name='Последний назначенный исполнитель'),
        ),
        migrations.AddField(
            model_name='orderworkflowrule',
            name='moderator_groups',
            field=models.ManyToManyField(blank=True, related_name='order_workflow_rules', to='auth.group', verbose_name='Группы модераторов'),
        ),
        migrations.AddField(
            model_name='orderworkflowrule',
            name='technical_group',
            field=models.ForeignKey(blank=True, help_text='Не влияет на выбор исполнителя. Используется как организационный контекст и фильтр.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_workflow_rules', to='users.technicalgroup', verbose_name='Техническая группа'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_order_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['owner', 'created_at'], name='orders_order_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['content_type', 'object_id'], name='orders_order_ct_object_idx'),
        ),
    ]
