# Generated by Django 6.0.8 on 2026-09-17 06:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('brand', models.CharField(max_length=255, verbose_name='Марка')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('state_number', models.CharField(max_length=255, unique=True, verbose_name='Гос. номер')),
                ('mileage', models.DecimalField(decimal_places=2, default=0, help_text='Обновляется каждый день в 00:00', max_digits=10, verbose_name='Пробег(км)')),
                ('engine_hours', models.DecimalField(decimal_places=2, default=0, help_text='Обновляется каждый день в 00:00', max_digits=10, verbose_name='Моточасы(ч)')),
                ('interval_oil_change', models.IntegerField(default=10000, verbose_name='Интервал замены масла(км)')),
                ('interval_timing_belt_change', models.IntegerField(default=90000, verbose_name='Интервал замены ремня ГРМ(км)')),
                ('interval_timing_roller_change', models.IntegerField(default=90000, verbose_name='Интервал замены роликов ГРМ(км)')),
                ('tracker_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Идентификатор маячка')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='garage.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('type_of_work', models.PositiveSmallIntegerField(choices=[(0, 'Замена масла ДВС'), (1, 'Замена ремня ГРМ'), (2, 'Замена ролика ГРМ')], default=0, verbose_name='Тип работ')),
                ('notes', models.TextField(blank=True, max_length=255, null=True, verbose_name='Примечания')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата обслуживания')),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Пробег(км)')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='garage.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Запись в журнале автомобиля',
                'verbose_name_plural': 'Журнал автомобиля',
            },
        ),
    ]
