# Generated by Django 6.0.8 on 2026-09-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('public_reply', 'Public reply'), ('internal_note', 'Internal note'), ('system_event', 'System event')], db_index=True, max_length=32)),
                ('visibility', models.CharField(choices=[('requester_and_staff', 'Requester and staff'), ('staff_only', 'Staff only')], db_index=True, max_length=32)),
                ('system_event_type', models.CharField(blank=True, choices=[('ticket_created', 'Ticket created'), ('status_changed', 'Status changed'), ('assignment_changed', 'Assignment changed'), ('priority_changed', 'Priority changed'), ('message_deleted', 'Message deleted')], max_length=64)),
                ('body', models.TextField(blank=True)),
                ('body_rendered', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order message',
                'verbose_name_plural': 'Order messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_communication/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Order message attachment',
                'verbose_name_plural': 'Order message attachments',
            },
        ),
        migrations.CreateModel(
            name='OrderThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_public_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_internal_note_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Order thread',
                'verbose_name_plural': 'Order threads',
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderThreadReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('unread_count_hint', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order thread read state',
                'verbose_name_plural': 'Order thread read states',
            },
        ),
    ]
