# Generated by Django 6.0.8 on 2026-09-17 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_communication', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_order_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_order_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermessageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='order_communication.ordermessage'),
        ),
        migrations.AddField(
            model_name='ordermessageattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_order_message_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderthread',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderthread',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_thread', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordermessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='order_communication.orderthread'),
        ),
        migrations.AddField(
            model_name='orderthreadreadstate',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='order_communication.ordermessage'),
        ),
        migrations.AddField(
            model_name='orderthreadreadstate',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='order_communication.orderthread'),
        ),
        migrations.AddField(
            model_name='orderthreadreadstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_thread_read_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ordermessageattachment',
            index=models.Index(fields=['message', 'created_at'], name='oc_att_message_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermessage',
            index=models.Index(fields=['thread', 'created_at'], name='oc_msg_thr_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermessage',
            index=models.Index(fields=['thread', 'visibility', 'created_at'], name='oc_msg_thr_vis_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermessage',
            index=models.Index(fields=['thread', 'message_type', 'created_at'], name='oc_msg_thr_type_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermessage',
            index=models.Index(fields=['thread', 'is_deleted', 'created_at'], name='oc_msg_thr_del_cr_idx'),
        ),
        migrations.AddConstraint(
            model_name='ordermessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('message_type', 'system_event'), ('system_event_type__gt', '')), models.Q(('message_type', 'system_event'), _negated=True), _connector='OR'), name='oc_msg_system_event_type_required'),
        ),
        migrations.AddIndex(
            model_name='orderthreadreadstate',
            index=models.Index(fields=['user', 'last_read_at'], name='oc_read_user_last_read_idx'),
        ),
        migrations.AddIndex(
            model_name='orderthreadreadstate',
            index=models.Index(fields=['thread', 'user'], name='oc_read_thread_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderthreadreadstate',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='oc_read_thread_user_unique'),
        ),
    ]
