# Generated by Django 6.0.8 on 2026-09-17 06:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Высокий'), (2, 'Средний'), (3, 'Низкий')], default=1, verbose_name='Приоритет')),
                ('last_assigned_specialist_index', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Последний назначенный специалист')),
            ],
            options={
                'verbose_name': 'Группа специалистов',
                'verbose_name_plural': 'Группы специалистов',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='Полное имя')),
                ('departament', models.CharField(blank=True, max_length=100, verbose_name='Подразделение')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('cabinet', models.CharField(blank=True, max_length=50, verbose_name='Кабинет')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('post', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                ('tlg_id', models.BigIntegerField(blank=True, null=True, verbose_name='Телеграм ID')),
                ('inform_me', models.BooleanField(default=False, help_text='Отправка уведомлений пользователю в телеграм по его ID.', verbose_name='Уведомлять в телеграм')),
                ('telegram_qrcode', models.ImageField(blank=True, null=True, upload_to='users/qrcode/telegram/', verbose_name='Telegram QRcode')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SupportSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_specialists', to=settings.AUTH_USER_MODEL, verbose_name='Специалист')),
                ('technical_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialists', to='users.technicalgroup', verbose_name='Техническая группа')),
            ],
            options={
                'verbose_name': 'Специалист поддержки',
                'verbose_name_plural': 'Специалисты поддержки',
            },
        ),
    ]
