# Generated by Django 6.0.4 on 2026-04-24 09:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "text_answer",
                    models.TextField(blank=True, verbose_name="Текстовый ответ"),
                ),
                (
                    "rating_value",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Оценка"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на вопрос",
                "verbose_name_plural": "Ответы на вопросы",
                "ordering": ["question__order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SurveyOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "text",
                    models.CharField(max_length=255, verbose_name="Текст варианта"),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Техническое значение"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответа",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SurveyCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активна"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Показывать с"
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Показывать до"
                    ),
                ),
                (
                    "popup_title",
                    models.CharField(max_length=255, verbose_name="Заголовок popup"),
                ),
                (
                    "popup_text",
                    models.TextField(blank=True, verbose_name="Текст popup"),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100, verbose_name="Приоритет"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_survey_campaigns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кампания опроса",
                "verbose_name_plural": "Кампании опросов",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswerOptionSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_options",
                        to="surveys.surveyanswer",
                        verbose_name="Ответ",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multiple_choice_selections",
                        to="surveys.surveyoption",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выбранный вариант multiple choice",
                "verbose_name_plural": "Выбранные варианты multiple choice",
            },
        ),
        migrations.AddField(
            model_name="surveyanswer",
            name="selected_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="single_choice_answers",
                to="surveys.surveyoption",
                verbose_name="Выбранный вариант",
            ),
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("rating", "Оценка 1-5"),
                            ("single_choice", "Один вариант"),
                            ("multiple_choice", "Несколько вариантов"),
                            ("text", "Текст"),
                        ],
                        max_length=32,
                        verbose_name="Тип вопроса",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Обязательный"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=1, verbose_name="Порядок"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="surveys.surveycampaign",
                        verbose_name="Кампания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос кампании",
                "verbose_name_plural": "Вопросы кампаний",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="surveyoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="surveys.surveyquestion",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AddField(
            model_name="surveyanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="surveys.surveyquestion",
                verbose_name="Вопрос",
            ),
        ),
        migrations.CreateModel(
            name="SurveySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Отправлено"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="surveys.surveycampaign",
                        verbose_name="Кампания",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прохождение опроса",
                "verbose_name_plural": "Прохождения опросов",
                "ordering": ["-submitted_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="surveyanswer",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="surveys.surveysubmission",
                verbose_name="Прохождение",
            ),
        ),
        migrations.AddIndex(
            model_name="surveycampaign",
            index=models.Index(
                fields=["is_active", "starts_at", "ends_at"], name="srv_camp_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveycampaign",
            index=models.Index(
                fields=["priority", "created_at"], name="srv_camp_prio_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyansweroptionselection",
            constraint=models.UniqueConstraint(
                fields=("answer", "option"), name="srv_answer_option_sel_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyquestion",
            constraint=models.UniqueConstraint(
                fields=("campaign", "order"), name="srv_q_campaign_order_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyoption",
            constraint=models.UniqueConstraint(
                fields=("question", "order"), name="srv_opt_question_order_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyoption",
            constraint=models.UniqueConstraint(
                fields=("question", "value"), name="srv_opt_question_value_uq"
            ),
        ),
        migrations.AddIndex(
            model_name="surveysubmission",
            index=models.Index(
                fields=["campaign", "submitted_at"], name="srv_sub_campaign_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveysubmission",
            index=models.Index(
                fields=["user", "submitted_at"], name="srv_sub_user_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveysubmission",
            constraint=models.UniqueConstraint(
                fields=("campaign", "user"), name="srv_sub_campaign_user_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyanswer",
            constraint=models.UniqueConstraint(
                fields=("submission", "question"), name="srv_answer_sub_question_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyanswer",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("rating_value__isnull", True),
                    models.Q(("rating_value__gte", 1), ("rating_value__lte", 5)),
                    _connector="OR",
                ),
                name="srv_answer_rating_range_ck",
            ),
        ),
    ]
