# Generated by Django 6.0.8 on 2026-09-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EthernetSocketConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('pc_name', models.CharField(max_length=155, unique=True, verbose_name='Имя устройства (кабинет)')),
                ('ethernet_socket', models.CharField(max_length=155, unique=True, verbose_name='Номер розетки')),
                ('switch_num', models.PositiveSmallIntegerField(default=0, verbose_name='Номер коммутатора')),
                ('switch_port', models.PositiveSmallIntegerField(default=0, verbose_name='Порт коммутатора')),
            ],
            options={
                'verbose_name': 'Подключение интернет розеток',
                'verbose_name_plural': 'Подключение интернет розеток',
                'ordering': ['pc_name', 'ethernet_socket'],
            },
        ),
    ]
