# Generated by Django 6.0.8 on 2026-09-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Создание заявки'), ('order_requires_review', 'Заявка требует разбора'), ('order_status_changed', 'Изменение статуса заявки'), ('order_completed', 'Заявка выполнена'), ('order_reopened', 'Заявка возобновлена'), ('order_assigned', 'Назначение исполнителя'), ('order_unassigned', 'Снятие исполнителя'), ('order_sent_to_service_organization', 'Заявка передана подрядчику'), ('order_comment_added', 'Добавлен комментарий'), ('order_comment_updated', 'Обновлён комментарий'), ('order_requester_updated', 'Заявитель обновил заявку'), ('order_details_changed', 'Изменены важные поля заявки'), ('order_sla_reminder', 'Напоминание о сроке ответа')], default='order_details_changed', max_length=64)),
                ('title', models.CharField(max_length=254)),
                ('body', models.TextField(db_column='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='timestamp', db_index=True)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
